### ISSUE TITLE
Saving as different formats / Adding background colors

### ISSUE THREAD

**Issue by clodewyks** [MarvinKlein1508/SignaturePad#10]
We have recently upgraded our app to use your component instead of an old, outdated javascript option. Thank you for the great component.

The one item we are missing is the ability to save to jpg or add a background to the png, the reason for this requirement I believe is quite specific to our use case; using the image in crystal reports which does not support transparent png.

Using the old component which has dissapeared off github we could achieve this by setting it up as follows:

`var pad = new SignaturePad(canvas, { backgroundColor: "rgb(255,255,255)" });`

When rendering the signatures in crystal reports from this component, they show with a black background

![image](https://github.com/MarvinKlein1508/SignaturePad/assets/5906783/1efaa084-355c-4a8c-85c9-85e247e529fd)

Is there a way to add a white background to the signature?

**Comment by MarvinKlein1508** [comment]
@clodewyks I've just published an update to the component now which allows you to set the background color. You can provide it within the `SignaturePadOptions`

You should be able to convert the base64 string to whatever format you'll need.

**Comment by clodewyks** [comment]
Thank you @MarvinKlein1508 , tested and deployed.

Thank you for the fast response
