### ISSUE TITLE
Custom height and clear programmatically

### ISSUE THREAD

**Issue by mkzaker** [MarvinKlein1508/SignaturePad#12]
how i can set custom height and clear canvas programmatically?

**Comment by MarvinKlein1508** [comment]
You can clear the canvas by simply setting your bound property to an empty array.

To change the size of the canvas you can override the CSS class signaturepad and set your custom height and width.

**Comment by MarvinKlein1508** [comment]
You can now define the width and height bei either applying `width` or `height` attributes or by defining a custom `style` attribute on the component itself
