### ISSUE TITLE
How to change button styling?

### ISSUE THREAD

**Issue by cryo75** [MarvinKlein1508/SignaturePad#13]
Is it possible to change the class / style of the clear button?

**Comment by MarvinKlein1508** [comment]
Right now it's not possible. 

Would you rather have a class which you can override or a class which can be specified ?

**Comment by cryo75** [comment]
A class that can be specified would be better.

**Comment by MarvinKlein1508** [comment]
Done in v7.4.0

**Comment by cryo75** [comment]
Thanks.
