### ISSUE TITLE
Unhandled exception when rotating mobile device

### ISSUE THREAD

**Issue by cryo75** [MarvinKlein1508/SignaturePad#15]
The following exception is thrown (presumably when the user rotates the mobile):

> [RemoteRenderer] Unhandled exception rendering component: undefined is not an object (evaluating 'screen.orientation.onchange = function () {
    dotNetHelper.invokeMethodAsync('UpdateImage');
}')
module code@https://mywebsite/_content/Blazor.SignaturePad/sigpad.interop.js:17:19
evaluate@[native code]
moduleEvaluation@[native code]
@[native code]
asyncFunctionResume@[native code]
@[native code]
promiseReactionJobWithoutPromise@[native code]
promiseReactionJob@[native code]
Microsoft.JSInterop.JSException: undefined is not an object (evaluating 'screen.orientation.onchange = function () {
    dotNetHelper.invokeMethodAsync('UpdateImage');
}')
module code@https://mywebsite/_content/Blazor.SignaturePad/sigpad.interop.js:17:19
evaluate@[native code]
moduleEvaluation@[native code]
@[native code]
asyncFunctionResume@[native code]
@[native code]
promiseReactionJobWithoutPromise@[native code]
promiseReactionJob@[native code]
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at SignaturePad.SignaturePad.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

**Comment by MarvinKlein1508** [comment]
I'm not ablte to reproduce this issue. Can you provide me with more details on how to trigger this exception? 

I've tried it on multiple tablets and phones and it worked fine for me.

Perhaps a small repository or a video on how to trigger this would help.

**Comment by cryo75** [comment]
Even I can't reproduce the problem. I will keep on trying.

**Comment by cryo75** [comment]
Will let you know if it's fixed.
