### ISSUE TITLE
.NET publish command fails for .NET6 docker image 

### ISSUE THREAD

**Issue by adityar-git** [MarvinKlein1508/SignaturePad#16]
Hi,

I have a docker file where I am building my SignaturePad application where it failed during the dotnet publish command. When I upgrade the docker image to .NET7 seems to be working. 

**.Net6 SDK Docker Image**
`mcr.microsoft.com/dotnet/sdk:6.0.413-bullseye-slim`

**Error**
`#19 36.83 /src/Client.Core/Microsoft.NET.Sdk.Razor.SourceGenerators/Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator/Containers_Viewer_Items_SignatureResponseItemViewer_razor.g.cs(326,50): error CS0426: The type name 'SignaturePad' does not exist in the type 'SignaturePad' [/src/Client.Core/Client.Core.csproj]`

**Comment by MarvinKlein1508** [comment]
Hi @adityar-git 

SignaturePad needs at least .NET 6.0.20. According to your docker image you are using 6.0.4

**Comment by adityar-git** [comment]
Ah that makes sense. Thanks
