### ISSUE TITLE
Options error

### ISSUE THREAD

**Issue by andySF** [MarvinKlein1508/SignaturePad#24]
Any idea how to get rid of this error. It builds successfully but I hate the red line.  

<img width="391" alt="image" src="https://github.com/MarvinKlein1508/SignaturePad/assets/772173/cac8bf75-3e19-40e5-9d35-8b7877feb588">

Argument type 'SignaturePad.SignaturePadOptions' is not assignable to parameter type 'SignaturePadOptions'

`    private SignaturePadOptions _options = new ()
    {
        LineCap = LineCap.Round,
        LineJoin = LineJoin.Round,
        LineWidth = 5
    };`

**Comment by MarvinKlein1508** [comment]
This should work. Are you able to share this code file?

It works in the options demo:
https://github.com/MarvinKlein1508/SignaturePad/blob/master/Demos.Core/SignaturePadDemos/OptionsDemo.razor

**Comment by MarvinKlein1508** [comment]
I'm closing this one for now since there was no more activity. Please create another issue if this still persists.
