### ISSUE TITLE
using SignaturePad not recognized after installing on 8.0.0

### ISSUE THREAD

**Issue by SpodoY** [MarvinKlein1508/SignaturePad#25]
As the titles says, for some reason, after installing the Package via Nuget, it tells me it's not recognized inside _Imports.razor:
![image](https://github.com/MarvinKlein1508/SignaturePad/assets/72346498/08c62ea2-5d9b-4fb2-af4d-ac381d60a5f0)
![image](https://github.com/MarvinKlein1508/SignaturePad/assets/72346498/1cb1b38b-8f87-4874-bd84-590e253297d4)
![image](https://github.com/MarvinKlein1508/SignaturePad/assets/72346498/692ff6f3-596f-4e6f-9a2f-9ffd3af3e8e1)

**Comment by MarvinKlein1508** [comment]
Which version of .NET are you using?

**Comment by SpodoY** [comment]
Microsoft Visual Studio Community 2022
Version 17.7.3
VisualStudio.17.Release/17.7.3+34024.191
Microsoft .NET Framework
Version 4.8.09032

Installierte Version: Community

ASP.NET and Web Tools   17.7.273.65229
ASP.NET and Web Tools

Azure App Service-Tools v3.0.0   17.7.273.65229
Azure App Service-Tools v3.0.0

Azure Functions and Web Jobs Tools   17.7.273.65229
Azure Functions and Web Jobs Tools

C#-Tools   4.7.0-3.23416.8+43b0b05cc4f492fd5de00f6f6717409091df8daa
C#-Komponenten, die in der IDE verwendet werden. Abhängig von Ihrem Projekttyp und den zugehörigen Einstellungen kann eine andere Version des Compilers verwendet werden.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.4.34 (main@d5ab18b)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Mono Debugging for Visual Studio   17.7.27 (547ea6f)
Support for debugging Mono processes with Visual Studio.

NuGet-Paket-Manager   6.7.0
NuGet-Paket-Manager in Visual Studio. Weitere Informationen zu NuGet finden Sie unter https://docs.nuget.org/.

Razor (ASP.NET Core)   17.7.3.2333001+0ab18affdf2a37647768d0e25f5f021bee6257a1
Stellt Sprachdienste für ASP.NET Core Razor bereit.

SQL Server Data Tools   17.7.10.1
Microsoft SQL Server Data Tools

TypeScript-Tools   17.0.20628.2001
TypeScript-Tools für Microsoft Visual Studio

Visual Basic-Tools   4.7.0-3.23416.8+43b0b05cc4f492fd5de00f6f6717409091df8daa
Visual Basic-Komponenten, die in der IDE verwendet werden. Abhängig von Ihrem Projekttyp und den zugehörigen Einstellungen kann eine andere Version des Compilers verwendet werden.

Visual F# Tools   17.7.0-beta.23314.10+e612cf93b989503c89e3a5830090062b7ab5e143
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
KI-gestützte Entwicklung für Visual Studio.

VisualStudio.DeviceLog   1.0
Informationen zum Paket

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSPackage-Erweiterung   1.0
Detaillierte Informationen zur VSPackage Visual Studio-Erweiterung

Xamarin   17.7.0.216 (d17-7@133ddef)
Visual Studio-Erweiterung, um Entwicklung für Xamarin.iOS und Xamarin.Android zu ermöglichen.

Xamarin Designer   17.7.3.9 (remotes/origin/d17-7@796d191def)
Visual Studio-Erweiterung zum Aktivieren der Xamarin Designer-Tools in Visual Studio.

Xamarin.Android SDK   13.2.1.2 (d17-5/a8a26c7)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: d9a6e87
    Java.Interop: xamarin/java.interop/d17-5@149d70fe
    SQLite: xamarin/sqlite/3.40.1@68c69d8
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-5@ca1552d

**Comment by MarvinKlein1508** [comment]
And your project? You can see it when you double click it in Visual Studio. For example:
![grafik](https://github.com/MarvinKlein1508/SignaturePad/assets/32510006/c7d22780-8f0c-478b-9e6b-063fdbb9a44a)

**Comment by SpodoY** [comment]
Sorry, relatively new to this, 6.0

**Comment by MarvinKlein1508** [comment]
@SpodoY v8.0.0 only runs on .NET 8. For .NET 6 use the previous version.

**Comment by SpodoY** [comment]
Thanks a lot!
