### ISSUE TITLE
SignaturePad rotate vertical

### ISSUE THREAD

**Issue by Dsalazar09** [MarvinKlein1508/SignaturePad#28]
Hello @MarvinKlein1508 .

Can this component be rotated so that it is vertical? It is to be implemented in a MAUI BLAZOR application, and if it will remain on the screen it would be great.

I did something with CSS and it does rotate but at the time of writing it doesn't line where it is.

Do you have any idea how it can be solved?

**Comment by MarvinKlein1508** [comment]
You should be able to overrite the CSS values for width and height. They are documented in the README file.

Basically the component renders into the size of the canvas.

**Comment by Dsalazar09** [comment]
Very good Marvin. It can be done by modifying the height with CSS and when saving you just have to rotate the signature.

Another question: by chance can the button: Clear signature be given a color?

Is it possible to change the color of the clear signature button?
![f1](https://github.com/MarvinKlein1508/SignaturePad/assets/57144049/c84b02c6-d439-45dc-9002-c0241c01d36b)

**Comment by MarvinKlein1508** [comment]
You can provide a custom class for the button by setting the `ClearButtonClass` parameter.

**Comment by Dsalazar09** [comment]
@MarvinKlein1508  thank you so much
