### ISSUE TITLE
Resolution of signature

### ISSUE THREAD

**Issue by JosipNizetic** [MarvinKlein1508/SignaturePad#29]
Hello,

Is it possible to change the frequency of point acquisition? As you can see in the image below, if we write fast, we get straight lines, like linear interpolation between two points:

![image](https://github.com/MarvinKlein1508/SignaturePad/assets/63609051/ed46cf82-c745-4202-ac4c-df0599a21293)

There is also a short movie showing the process:

https://github.com/MarvinKlein1508/SignaturePad/assets/63609051/e302db27-ada9-4f8b-9627-647a6b23388f

**Comment by MarvinKlein1508** [comment]
@JosipNizetic thanks for your request.

Right now I don't know any way to change this. In my tests this didn't happend at all. Which device and OS are you using?

**Comment by JosipNizetic** [comment]
Thank you for response. 

I tested on two pc - one intel nuc and other lenovo laptop. Both use windows 10 and external touch display. 

Just one question. How do you acquire points? On event or on timer?  

Mybe my display is problem.. I will try on other touch devices and see if it repeats.

Thank you for swift replays.

**Comment by MarvinKlein1508** [comment]
We use touch and mouse events to track begin, move and end

**Comment by JosipNizetic** [comment]
I tested your demo now on my mobile phone and works ok. I tested today on my laptop and was glitchy. It is 4k display so maybe that..

Let me do some more testing and come back if help is needed.  Probably next week when i return to office. 

Thank you, Josip

**Comment by MarvinKlein1508** [comment]
Hi @JosipNizetic please try v8.1.0 :)

**Comment by CodeGod911** [comment]
Hi @JosipNizetic 
I've found out as well for using edge it could limit the browser frametime to 100ms / 10fps if it has powersaving activated in its settings which can interfere with drawing accuratly => 10 pts /sec instead of 30-60-120-144 pts / sec depending on monitor refreshrate (mby 4k @ 30Hz?)

Good luck, Temps

**Comment by JosipNizetic** [comment]
Hi,

@MarvinKlein1508  thank you for all your effort. My colleague will update component and then i will test in Thursday. I will write if all is ok. @CodeGod911 thank you for input. I will check that also. 

Josip

**Comment by JosipNizetic** [comment]
Good morning,

I tested on several PC and everything works like a charm.

Thank you very much for your help.
