### ISSUE TITLE
problem adding to net7 wasm project

### ISSUE THREAD

**Issue by fontestad** [MarvinKlein1508/SignaturePad#31]
Good morning .

I feel a little stupid asking this question, but I haven't been able to add your component to my project.

As I read in the documentation I added 

Install-Package Blazor.SignaturePad

Check that it was added correctly to the project 

 <ItemGroup>
   <PackageReference Include="Blazor.SignaturePad" Version="8.0.6" />
   <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="7.0.19" />

But make it the next step 

Start by adding the following using statement to your root _Imports.razor.

@using SignaturePad

I get the error:
Severity Code Description File Project Line Status Suppressed Details
Error (active) CS0246 The type or namespace name 'SignaturePad' was not found (are you missing a using directive or assembly reference?)	

Tell them that for the test I am testing a net7 wasm

**Comment by MarvinKlein1508** [comment]
Hi @fontestad 

for .NET 7 please use version 7.5.0 of this library. All versions above this require .NET 8

**Comment by fontestad** [comment]
OK, perfect .

I thought the versions were compatible with each other.

My fault, sorry for the wasted time.
