### ISSUE TITLE
Smootness when drawing fast on 60fps and boundless mouse capture

### ISSUE THREAD

**Issue by CodeGod911** [MarvinKlein1508/SignaturePad#33]
Great Blazor Component thanks a lot.
For our usecase we needed smoother results and better handling if a user draws out of bounds. I made some improvements and if you're interrested i could share my changes. They're not perfectly refined though.
![image](https://github.com/MarvinKlein1508/SignaturePad/assets/58259484/301592fb-b08e-4ae4-b8af-6c57749cdb81)
vs
![image](https://github.com/MarvinKlein1508/SignaturePad/assets/58259484/e423b658-cb01-4b38-a538-b0a6d86d28f7)

![image](https://github.com/MarvinKlein1508/SignaturePad/assets/58259484/439636ac-5924-40e8-8fe2-0db7db50057b)
vs
![image](https://github.com/MarvinKlein1508/SignaturePad/assets/58259484/53adea08-f758-41d4-af8b-359cfef3b950)

**Comment by CodeGod911** [comment]
just saw that https://github.com/MarvinKlein1508/SignaturePad/issues/29 could be related

**Comment by MarvinKlein1508** [comment]
Feel free to create a PR and I'll take a look :)

**Comment by CodeGod911** [comment]
Should i fork or can i create a branch? Clueless Github user here :)

What im not content with is having to redraw every frame even when not drawing. But as i analyzed it uses almost no performance. But i found the getImage of the (to my knowledge) unused CustomEvent sigpad.move uses a lot of frametime and could be an issue on slower systems and i recommend discarding the details parameter it if not needed.
![image](https://github.com/MarvinKlein1508/SignaturePad/assets/58259484/6d8a6208-586b-4f02-9546-f8cb13e2c9d5)

**Comment by MarvinKlein1508** [comment]
@CodeGod911 fork it.
