### ISSUE TITLE
Add support for dotnet 6.0

### ISSUE THREAD

**Issue by ghockx1p** [MarvinKlein1508/SignaturePad#4]
I really like this SignaturePad and would like to use it in my dotnet 6.0 Blazor wasm project. But this package is targeted on dotnet 7.0 so I can't use it. The SignaturePad code seems to be working fine when targeted on dotnet 6.0 however.

Is there a reason behind not targeting dotnet 6.0?
If not would you appreciate a pull request that changes the target to dotnet 6.0?

**Comment by MarvinKlein1508** [comment]
No there is no real reason for .NET 7. I usually take the latest available .NET version when creating new projects, that's all.

Lower versions besides .NET 6 won't work because the async javascript streaming capabilities were introduced in .NET 6.

Feel free to do a pull request.

**Comment by MarvinKlein1508** [comment]
Merged and uploaded to NuGet. Should be available shortly.
