### ISSUE TITLE
Drawing on mobile devices hangs behind

### ISSUE THREAD

**Issue by MarvinKlein1508** [MarvinKlein1508/SignaturePad#40]
https://github.com/MarvinKlein1508/SignaturePad/assets/32510006/a7159b82-aac7-4e45-a437-38d5511afb2c

Tested on iPhone 15 Pro

**Comment by MarvinKlein1508** [comment]
@CodeGod911 any ideas?

**Comment by CodeGod911** [comment]
@MarvinKlein1508 On which browser is this; I tested Firefox, Chome on Android seems to work like a charm. I dont think it is because of the last bugfix (rectangle cuttoffs) as if the canvas is not full size and resizes on touch end. mby because of the capture in events?

**Comment by CodeGod911** [comment]
Mby this is related https://stackoverflow.com/questions/23202555/javascript-canvas-buffer-slow-performance-on-ios-safari-and-chrome

**Comment by CodeGod911** [comment]
seems to draw only the borders around the center of the lines when looking at it closely

**Comment by MarvinKlein1508** [comment]
It's Safari on mobile

**Comment by CodeGod911** [comment]
you could try activating the preventDefault() on the onMove eventhandler 
https://github.com/paperjs/paper.js/issues/633#issuecomment-172369502
![image](https://github.com/MarvinKlein1508/SignaturePad/assets/58259484/378bc73a-2a7f-4c85-90ce-18558d7e952d)

**Comment by CodeGod911** [comment]
I cant confirm sadly anything because i dont use IOS but what i could imagine is that the render method doesnt properly finish and is not in sync because it defaults to the last line where you have a timed callback instead of the browser animateFrame callback

**Comment by CodeGod911** [comment]
Was this an issue in 8.0.6

**Comment by MarvinKlein1508** [comment]
I'll verify

**Comment by CodeGod911** [comment]
Im thinking of getImage in the onmove event mby it forces a complete reder of the canvas and the events listening on document

**Comment by MarvinKlein1508** [comment]
@CodeGod911 I can actually reproduce it on Firefox on PC as well.

When adding this line I get the same behaviour, so perhaps my mobile phone has this version cached:
```js
ctx.clearRect(0, 0,  this._element.clientWidth ,this._element.clientHeight );
```
![drawing](https://github.com/MarvinKlein1508/SignaturePad/assets/32510006/fc0e7dd3-95d8-42c6-87de-d8386b2f63aa)

**Comment by CodeGod911** [comment]
this is not the same behaviour i can assure you this is the last line only being draw on leaving the drawing context. if you clear the context the already drawn lines are disposed and only drawn again if finished.

**Comment by CodeGod911** [comment]
https://stackoverflow.com/questions/8659748/html5-canvas-unexpected-effect-with-quadratic-curves

**Comment by CodeGod911** [comment]
More related stuff
https://stackoverflow.com/questions/71150996/why-does-canvas-arc-stroke-ends-distorted-in-safari-iphone-and-m1-mac

**Comment by MarvinKlein1508** [comment]
@CodeGod911 
I can also confirm that https://github.com/CodeGod911/SignaturePad/tree/bugfix/Antialiasing2 fixes this issue.

**Comment by CodeGod911** [comment]
@MarvinKlein1508 wtf didnt intend to :D luck i guess

**Comment by MarvinKlein1508** [comment]
Completed in v8.1.4
