### ISSUE TITLE
Microsoft.JSInterop.JSException: ctx is not defined

### ISSUE THREAD

**Issue by SirBirne** [MarvinKlein1508/SignaturePad#45]
I'm getting the following exception in the newest Version:

Microsoft.JSInterop.JSException: ctx is not defined ReferenceError: ctx is not defined at Sigpad.setImage (https://0.0.0.0/_content/Blazor.SignaturePad/sigpad.min.js?ver=8.1.4:147:13) at Module.setup (https://0.0.0.0/_content/Blazor.SignaturePad/sigpad.interop.js?ver=8.1.4:15:12) at https://0.0.0.0/_framework/blazor.webview.js:1:3050 at new Promise (<anonymous>) at g.beginInvokeJSFromDotNet (https://0.0.0.0/_framework/blazor.webview.js:1:3007) at https://0.0.0.0/_framework/blazor.webview.js:1:48020 at EventTarget.<anonymous> (<anonymous>:7:62) at EmbeddedBrowserWebView.<anonymous> (<anonymous>:1:43721) at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args) at Microsoft.JSInterop.JSObjectReferenceExtensions.InvokeVoidAsync(IJSObjectReference jsObjectReference, String identifier, Object[] args) at SignaturePad.SignaturePad.Setup() at SignaturePad.SignaturePad.OnAfterRenderAsync(Boolean firstRender) at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

Going to downgrade for now.

**Comment by MarvinKlein1508** [comment]
Will be fixed in v8.1.5. Thanks for reporting!
